// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package repository

import (
	"database/sql"
)

type Ingredient struct {
	ID     int32  `json:"id"`
	TypeID int32  `json:"type_id"`
	Title  string `json:"title"`
	Price  string `json:"price"`
}

type IngredientType struct {
	ID    int32          `json:"id"`
	Title sql.NullString `json:"title"`
	Code  sql.NullString `json:"code"`
}
